---
title: "pinellas-eviction-scraper-functions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

### Load Libraries

```{r results='hide'}
library(tidyverse) # Tidy functions
library(RSelenium) # Headless browser
library(XML) # For extracting info from HTML
library(seleniumPipes) # For additional Selenium features
library(rvest) # For extracting info from HTML
library(RCurl) # For extracting URL
library(janitor) # For cleaning up scraped data
library(reticulate) # For injecting Python
```

## Functions

### Check for text on page

```{r}

check_for_text <- function(text, xpath) {
  if(exists("remote_driver")){
    # Get page HTML source code (stores as list)
    pagehtml <- remote_driver$getPageSource()
    # Read in html as nodes
    nodes <- read_html(pagehtml[[1]])
    
    # Try to collect an element into a list
    temp <- remote_driver$findElements(using = "xpath",
                                       value = xpath)
    # If the list length is greater than 0, the element exists
    if(length(temp) > 0) {
      # print("Found the element.")
      if (as.character(temp[[1]]$getElementText()) == text) {
        return(TRUE)
      } else {
        # print("Element text doesn't match search.")
        return(FALSE)
      }
    } else {
      # print("Element not found.")
      return(FALSE)
    }
  } else {
    # print("No remote driver detected.")
    return(FALSE)
  }
}
# Test
# check_for_text(text = "Registered User Login",
#                xpath = "/html/body/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]/a[8]")
```

### Check for an element on a page

```{r}

check_for_element <- function(element_to_check, by = "xpath") {
  if(exists("remote_driver")){
    # Get page HTML source code (stores as list)
    pagehtml <- remote_driver$getPageSource()
    # Read in html as nodes
    nodes <- read_html(pagehtml[[1]])
    # Try to collect an element into a list
    temp <- remote_driver$findElements(using = by,
                                       value = element_to_check)
    # If the list length is greater than 0, the element exists
    if(length(temp) > 0) {
      # print("Found the element.")
      return(TRUE)
    } else {
      # print("Element not found.")
      return(FALSE)
    }
  } else {
    # print("No remote driver detected.")
    return(FALSE)
  }
}

```

### Send to webpage

```{r}

# Function to navigate to the Pinellas court system homepage
navigate_to_pinellas_courts_home <- function() {
  myurl <- remote_driver$navigate(
  "https://ccmspa.pinellascounty.org/PublicAccess/default.aspx")
}
```

### Log in functions

```{r}

# Function to check if at login screen
check_if_login_screen <- function(){
  if(check_for_element("SignOn", by = "name")){
    return(TRUE)
  } else {
    return(FALSE)
  }
}

# Function to log in to the Pinellas court system
login_action <- function() {
  # Locate and click the Registered User log-in
  temp <- remote_driver$findElement(using = "xpath",
                                    value ="/html/body/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]/a[8]")
  temp$clickElement()
  
  Sys.sleep(1)
  # Enter username
  temp <- remote_driver$findElement(using = "xpath",
                                    value = "/html/body/form/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]/table/tbody/tr[1]/td/input")
  temp$clickElement()
  temp$sendKeysToElement(list("REG01506"))
  
  # Enter password
  temp <- remote_driver$findElement(using = "xpath",
                                    value = "/html/body/form/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]/table/tbody/tr[3]/td/input")
  temp$clickElement
  temp$sendKeysToElement(list("9ZbdYbpxPt8"))
  
  Sys.sleep(1)
  # Click submit
  temp <- remote_driver$findElement(using = "xpath",
                                    value = "/html/body/form/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]/table/tbody/tr[6]/td/input")
  temp$clickElement()
}

login_to_pinellas_courts <- function() {
  # Check we're on the home page with the login link
  if(check_for_text(text = "Registered User Login", xpath = "/html/body/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]/a[8]") == TRUE) {
    print("login_to_pinellas_courts: Element found; able to log in.")
    login_action()
    } else {
      print("login_to_pinellas_courts: Element not found; returning to start.")
      # Go to the home page
      navigate_to_pinellas_courts_home()
      Sys.sleep(2)
      # Look for login link
      if(check_for_text(text = "Registered User Login", xpath = "/html/body/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]/a[8]") == TRUE) {
        login_action()
      } else {
        print("login_to_pinellas_courts: Already logged in.")
      }
    }
}

```

### Enter court case search functions

```{r}
# Function to enter All Case Records Search
enter_all_case_search_action <- function() {
  temp <- remote_driver$findElement(using = "xpath",
                                  value = "/html/body/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]/a[1]")
  temp$clickElement()
}

enter_all_case_search <- function() {
  # Check we're on the page with the All Case Records Search link
  if(check_for_text(text = "All Case Records Search", xpath = "/html/body/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]/a[1]") == TRUE) {
    print("enter_all_case_search: Element found; able to enter all case search.")
    enter_all_case_search_action()
    } else {
      print("enter_all_case_search: Element not found; returning to start.")
      # Go to the home page and log back in
      login_to_pinellas_courts()
      Sys.sleep(2)
      # Look for All Case Records Search link
      if(check_for_text(text = "All Case Records Search", xpath = "/html/body/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]/a[1]") == TRUE) {
        print("enter_all_case_search: Element found; able to enter all case search.")
        enter_all_case_search_action()
      } else {
        print("enter_all_case_search: Error. Could not find records search link.")
      }
    }
}

```

### Search within a date range

```{r}

# Function to set the date range
enter_date_range_action <- function(counter) {

    # Set search use "Date Filed" 
    temp <- remote_driver$findElement(using = "id",
                                      value = "DateFiled")
    temp$clickElement()
    
    ### Enter search criteria
    
    ## Dates
    # Select Starting Date field
    temp <- remote_driver$findElement(using = "xpath",
                                      value = "/html/body/form/table[4]/tbody/tr/td/table/tbody/tr[6]/td[2]/table/tbody/tr/td/div/table/tbody/tr/td/table/tbody/tr[6]/td[2]/table/tbody/tr/td[1]/input")
    temp$clickElement()
    
    # Clear text field
    temp$clearElement()
    
    # Input starting date
    temp$sendKeysToElement(list(dates_ls[[counter]][[1]]))
    
    # Select Ending Date field
    temp <- remote_driver$findElement(using = "xpath",
                                      value = "/html/body/form/table[4]/tbody/tr/td/table/tbody/tr[6]/td[2]/table/tbody/tr/td/div/table/tbody/tr/td/table/tbody/tr[6]/td[2]/table/tbody/tr/td[3]/input")
    temp$clickElement()
    
    # Clear text field
    temp$clearElement()
    
    # Input ending date
    temp$sendKeysToElement(list(dates_ls[[counter]][[2]]))
    
    ## Case Types
    # Choose "Delinquent Tenant/Eviction" cases
    temp <- remote_driver$findElement(using = "xpath",
                                      value = "/html/body/form/table[4]/tbody/tr/td/table/tbody/tr[11]/td[2]/table/tbody/tr/td/div/table/tbody/tr/td/table/tbody/tr/td[2]/select/option[6]")
    
    # Check whether it's already selected (JavaScript)
    selected_status <- remote_driver$executeScript(
      "return document.querySelector('#selCaseTypeGroups > option:nth-child(6)').selected", 
      args = list("dummy")
    )
    
    # If not selected, click it
    if (!selected_status[[1]]){
      temp$clickElement()
    }
    
    ## Submit
    temp <- remote_driver$findElement(using = "xpath",
                                      value = "/html/body/form/table[4]/tbody/tr/td/table/tbody/tr[14]/td[2]/input[1]")
    temp$clickElement()
    
    Sys.sleep(12)
}

# Function to implement date range entry
enter_date_range <- function(x){
  # Check we're on the page with the All Case Records Search title
  if(check_for_text(text = "All Case Records Search", xpath = "/html/body/form/table[3]/tbody/tr/td[2]/font") == TRUE) {
    print("enter_date_range: Element found; able to enter a date range.")
    enter_date_range_action(x)
    
    } else {
      # Go back a step (this function will regress back to the start if necessary)
      enter_all_case_search()
      Sys.sleep(2)
      # Look for All Case Records Search title
      if(check_for_text(text = "All Case Records Search", xpath = "/html/body/form/table[3]/tbody/tr/td[2]/font") == TRUE) {
        enter_date_range_action(x)
      } else {
        print("enter_date_range: Error. Unable to search date range.")
      }
    }
}

```

### Store basic case info

```{r}

## Function to store basic case info
store_basic_info_action <- function(counter) {
  # Get page HTML source code (stores as list)
  pagehtml <- remote_driver$getPageSource()
  
  # Get table
  cases_df <- readHTMLTable(
    pagehtml[[1]], # Pull the html from the list
    which = 6) # Get the right table (the 6th one holds the info we need)
  
  # Clean up table (slightly)
  cases_df_clean <- as_tibble(cases_df) %>%
    drop_na() %>%
    row_to_names(1) %>%
    mutate_if(is.factor, as.character)
  
  if (counter < 10){
    counter_ch <- paste0("00", as.character(counter))
  } else if (counter < 100) {
    counter_ch <- paste0("0", as.character(counter))
  } else {
    counter_ch <- as.character(counter)
  }
  
  # Store the table in a CSV
  write.csv(cases_df_clean, paste0('data/by-month/eviction_cases_', counter_ch, '.csv'))
}

# Function to implement basic info storing
# Checks for "Refine Search" to validate location
store_basic_info <- function(x) {
  if(check_for_text(text = "Refine Search", xpath = "/html/body/table[2]/tbody/tr/td/table/tbody/tr/td[1]/font/a[6]") == TRUE) {
    print("store_basic_info: Element found; able to store info.")
    store_basic_info_action(x)
    } else {
      print("store_basic_info: Element not found; returning to start.")
      # Go to the home page and log back in
      login_to_pinellas_courts()
      Sys.sleep(2)
      enter_all_case_search()
      Sys.sleep(1)
      # Look for All Case Records Search link
      if(check_for_text(text = "Refine Search", xpath = "/html/body/table[2]/tbody/tr/td/table/tbody/tr/td[1]/font/a[6]") == TRUE) {
        store_basic_info_action(x)
      } else {
        print("store_basic_info: Error. Could not find requested text.")
      }
    }
}
```

